### ISSUE TITLE
Implement + Optimize LongInt Division

### ISSUE THREAD

**Issue by birdbrainswagtrain** [SwadicalRag/wasm2lua#17]
Only half of the longint division routines are implemented, only one is implemented correctly, and zero are implemented in a good way. First implement the rest correctly, then optimize. Use the same algorithm as in long.js, which has a Lua version floating around somewhere.

- [x] Signed division
- [x] Unsigned division

**Comment by notcake** [comment]
once this issue is resolved you will truly understand my suffering
