### ISSUE TITLE
Zero initialize locals

### ISSUE THREAD

**Issue by Rerumu** [SwadicalRag/wasm2lua#33]
WebAssembly expects locals (but not parameters) in a function body to be initialized to `0` by default. `wasm2lua` currently initializes them as `nil` which causes code that relies on this invariant to break.

This [minimal example](https://github.com/SwadicalRag/wasm2lua/files/7697929/reproducible.zip) is valid and should return `0`, but returns `nil` instead.

**Comment by SwadicalRag** [comment]
Thank you

**Comment by SwadicalRag** [comment]
Actually, hold on, this should have already worked prior to the fix since wasm2lua checks if variables are accessed before they are initialised and auto-initialises them to 0

**Comment by SwadicalRag** [comment]
wasm2lua@0.8.8
![image](https://user-images.githubusercontent.com/10724598/145696411-a60dcf0c-cb89-494e-b954-50cbad8ab348.png)

wasm2lua@0.8.9
![image](https://user-images.githubusercontent.com/10724598/145696406-8c54002c-aef1-48df-87b4-7f905f5c38bf.png)

**Comment by SwadicalRag** [comment]
I'll rollback the code.  0.8.9 will initialise all non-parametric locals to 0, but it does so at the cost of increased code size.

This is what happens when I try and go edit code I haven't touched in years

**Comment by Rerumu** [comment]
That is interesting; the issue is an uninitialized variable for sure but possibly because of a buggy heuristic instead. The repro I provided is the same one I used when I found the same issue on a similar project, my bad for not testing if that one specifically caused it.

I have a larger repro that definitely breaks that I can provide if necessary.

**Comment by SwadicalRag** [comment]
I'll have a poke around and see what I find
