### ISSUE TITLE
Use manually compiled luajit in Travis CI

### ISSUE THREAD

**Issue by SwadicalRag** [SwadicalRag/wasm2lua#8]
The builds are randomly failing probably because the luajit vm from the package manager is not correctly compiled.

**Comment by birdbrainswagtrain** [comment]
I had some pretty bad issues using the LuaJIT from my package manager as well as trying to compile it myself. It crashed when the JIT was turned on, but I didn't try to investigate why.

**Comment by SwadicalRag** [comment]
We haven't had any random failures in a while. Marking this issue as invalid.
